name: The point of this
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  cargo_clippy:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: "never"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
      - uses: antifuchs/rust-problem-matchers@clippy-regex
      - run: cargo clippy -- -D warning
        working-directory: .
